def f(x: int, /, y: int, z: int = ...) -> None: ...
def g(x: int = ..., /, y: int = ...) -> None: ...
def h(x: int, /, y: int = ..., z: int = ...) -> None: ...
def two_pos_only(x: int, y: str = ..., /) -> None: ...
