name: Documentation Build

on: [push, pull_request]

jobs:
  build:
    # We want to run on external PRs, but not on our own internal PRs as they'll be run
    # by the push to the branch. Without this if check, checks are duplicated since
    # internal PRs match both the push and pull_request events.
    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
      github.repository

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up latest Python
        uses: actions/setup-python@v5

      - name: Install dependencies
        run: |
          # With newer versions of pip and setuptools, codemod fails to install
          python -m pip install --upgrade 'pip<25' 'setuptools<77' wheel
          python -m pip install -e .
          python -m pip install -r "docs/requirements.txt"
      - name: Build documentation
        run: sphinx-build -a -b html -W --keep-going docs/ docs/_build
